[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.127.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GIT_SUBMODULE_STRATEGY = "recursive"

[context.split1]
command = "hugo"

[context.split1.environment]
HUGO_VERSION = "0.127.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo"

[context.deploy-preview.environment]
HUGO_VERSION = "0.127.0"

[context.branch-deploy]
command = "hugo"

[context.branch-deploy.environment]
HUGO_VERSION = "0.127.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
